"""change positions premery key to id 

Revision ID: 56152ede8e8d
Revises: 5d0463284f9e
Create Date: 2025-01-25 11:38:23.544696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56152ede8e8d'
down_revision: Union[str, None] = '5d0463284f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    op.drop_constraint('employee_office_department_name_fkey', 'employee', type_='foreignkey')
    op.drop_constraint('employee_retail_position_name_fkey', 'employee', type_='foreignkey')
    op.drop_constraint('employee_store_position_name_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'retail_position', ['retail_position_name'], ['id'])
    op.create_foreign_key(None, 'employee', 'office_department', ['office_department_name'], ['id'])
    op.create_foreign_key(None, 'employee', 'store_position', ['store_position_name'], ['id'])
    op.add_column('office_department', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('retail_position', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('store_position', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_position', 'id')
    op.drop_column('retail_position', 'id')
    op.drop_column('office_department', 'id')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_store_position_name_fkey', 'employee', 'store_position', ['store_position_name'], ['short_name'])
    op.create_foreign_key('employee_retail_position_name_fkey', 'employee', 'retail_position', ['retail_position_name'], ['short_name'])
    op.create_foreign_key('employee_office_department_name_fkey', 'employee', 'office_department', ['office_department_name'], ['short_name'])
    # ### end Alembic commands ###
