"""field department to position OfficeDep

Revision ID: 5d0463284f9e
Revises: 72807afb4f04
Create Date: 2025-01-24 15:31:17.775603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5d0463284f9e'
down_revision: Union[str, None] = '72807afb4f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_department', sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('office_department', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_department', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('office_department', 'position')
    # ### end Alembic commands ###
