"""add foreign key

Revision ID: 72807afb4f04
Revises: 97bceec2278d
Create Date: 2025-01-23 22:08:20.034070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72807afb4f04'
down_revision: Union[str, None] = '97bceec2278d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('district', sa.Column('region_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'district', 'region', ['region_id'], ['id'])
    op.add_column('office_department', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'office_department', 'location', ['location_id'], ['id'])
    op.add_column('region', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'region', 'country', ['country_id'], ['id'])
    op.add_column('retail_position', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'retail_position', 'location', ['location_id'], ['id'])
    op.add_column('store_position', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'store_position', 'location', ['location_id'], ['id'])
    op.add_column('task', sa.Column('location_id', sa.Integer(), nullable=False))
    op.drop_constraint('task_departament_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'location', ['location_id'], ['id'])
    op.drop_column('task', 'departament')
    op.add_column('ticket', sa.Column('location_id', sa.Integer(), nullable=False))
    op.drop_constraint('ticket_departament_fkey', 'ticket', type_='foreignkey')
    op.create_foreign_key(None, 'ticket', 'location', ['location_id'], ['id'])
    op.drop_column('ticket', 'departament')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('departament', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.create_foreign_key('ticket_departament_fkey', 'ticket', 'location', ['departament'], ['id'])
    op.drop_column('ticket', 'location_id')
    op.add_column('task', sa.Column('departament', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_departament_fkey', 'task', 'location', ['departament'], ['id'])
    op.drop_column('task', 'location_id')
    op.drop_constraint(None, 'store_position', type_='foreignkey')
    op.drop_column('store_position', 'location_id')
    op.drop_constraint(None, 'retail_position', type_='foreignkey')
    op.drop_column('retail_position', 'location_id')
    op.drop_constraint(None, 'region', type_='foreignkey')
    op.drop_column('region', 'country_id')
    op.drop_constraint(None, 'office_department', type_='foreignkey')
    op.drop_column('office_department', 'location_id')
    op.drop_constraint(None, 'district', type_='foreignkey')
    op.drop_column('district', 'region_id')
    # ### end Alembic commands ###
