"""add department to Ticket

Revision ID: 823ad12bbfde
Revises: 3f4572fbd15f
Create Date: 2025-01-27 14:52:51.266639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '823ad12bbfde'
down_revision: Union[str, None] = '3f4572fbd15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), default='Retail'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'department')
    # ### end Alembic commands ###
