"""add department, resipient to Task, manager to District 

Revision ID: b81941e86ec8
Revises: 823ad12bbfde
Create Date: 2025-01-27 19:57:44.439390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b81941e86ec8'
down_revision: Union[str, None] = '823ad12bbfde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('district', sa.Column('district_manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'district', 'employee', ['district_manager_id'], ['id'])
    op.add_column('task', sa.Column('task_recipient_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('ticket', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('task', 'department')
    op.drop_column('task', 'task_recipient_id')
    op.drop_constraint(None, 'district', type_='foreignkey')
    op.drop_column('district', 'district_manager_id')
    # ### end Alembic commands ###
